I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 76, in script
    outraMina "Moço, poderia me ajudar?"
Exception: Sayer 'outraMina' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 76, in script
    outraMina "Moço, poderia me ajudar?"
  File "C:\Users\giova\Downloads\renpy-7.3.5-sdk\renpy\ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\giova\Downloads\renpy-7.3.5-sdk\renpy\ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'outraMina' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
NDA 1.0
Wed Jun 03 19:41:20 2020
